name: Build and Test (Gradle)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Grant execute permission for Gradle wrapper
      run: chmod +x gradlew

    - name: Clean project
      run: ./gradlew clean

    - name: Build project
      run: ./gradlew build --no-daemon

    - name: Run unit tests
      run: ./gradlew test --no-daemon
